# Generated by Django 5.1 on 2024-09-03 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="createjob",
            options={},
        ),
        migrations.CreateModel(
            name="SurveyInitialDataDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("depth", models.IntegerField()),
                ("inc", models.DecimalField(decimal_places=2, max_digits=3)),
                ("AzG", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "job_number",
                    models.ForeignKey(
                        db_column="job_number",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.createjob",
                    ),
                ),
            ],
        ),
    ]
