# Generated by Django 5.1 on 2024-09-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_createjob_options_surveyinitialdatadetail"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="surveyinitialdatadetail",
            table="task_survey_initial_data_detail",
        ),
    ]
