# Generated by Django 5.1 on 2024-09-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_surveyinitialdatadetail_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="surveyinitialdatadetail",
            old_name="inc",
            new_name="Inc",
        ),
        migrations.RemoveField(
            model_name="surveyinitialdatadetail",
            name="job_number",
        ),
    ]
