# Generated by Django 5.1 on 2024-09-03 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_inc_surveyinitialdatadetail_inc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobinfo",
            name="job_number",
            field=models.ForeignKey(
                db_column="job_number",
                on_delete=django.db.models.deletion.PROTECT,
                to="api.createjob",
            ),
        ),
    ]
